### ISSUE TITLE
Cloudflare Error

### ISSUE THREAD

**Issue by magdev2022** [Kaliiiiiiiiii-Vinyzu/patchright-python#2]
Hello, I tested the Cloudflare challenge site. After completing the challenge, the page froze and became unresponsive.

I used this code. 

```
import time
from patchright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('https://2captcha.com/demo/cloudflare-turnstile-challenge')
    time.sleep(1000)
    browser.close()
```
![image](https://github.com/user-attachments/assets/177554bb-48ce-45ca-991a-f809ad982984)

**Comment by Vinyzu** [comment]
In the screenshot youve provided you can read "Verification successful" aswell as "Waiting for 2captcha.com to respond...".
Its obvious that this isnt an issue with patchright.

**Comment by magdev2022** [comment]
Is this a Playwright issue? None of the Cloudflare challenge sites are passing.

**Comment by magdev2022** [comment]
Why this issue closed?
I tested on 10 cloudflare sites, but all tests were failed.

**Comment by Vinyzu** [comment]
@magdev2022 Can you link me those cloudflare sites aswell as the feedback which you noticed of that you didnt pass please

But its most likely an external issue, e.g. your ip reputation, extensions, os setup etc.
Im reopening for now, but i dont think this is an issue with patchright.

**Comment by magdev2022** [comment]
https://2captcha.com/demo/cloudflare-turnstile-challenge
https://ezmanga.org/series/92ae7351c3e
https://lazytruyen.com/
https://coinsniper.net/new
....
pls check.

**Comment by VTTR** [comment]
additional note: 
`time.sleep(x)` might lead to some problems. [(see docs)](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state)

**Comment by batreller** [comment]
everything works just fine for me on https://2captcha.com/demo/cloudflare-turnstile-challenge

**Comment by Vinyzu** [comment]
Closing as invalid.
There have been no issues in passing cloudflare in my testing.
The Issue seems inconclusive. If the issue persist, please open another issue with a full reproducable example and a clear description of your setup & issue.

**Comment by ZzzYanSong** [comment]
I encountered a general problem. In the Linux environment, I passed the Cloudflare check through other plug-ins that simulate clicking, but I was stuck on the page that was verified successfully. But in my development machine (Windows) environment, it is normal.

**Comment by ZzzYanSong** [comment]
> 您好，我测试了 Cloudflare 挑战网站。完成挑战后，页面卡住了，没有任何响应。
> 
> 我使用了这个代码。
> 
> ```
> import time
> from patchright.sync_api import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch(headless=False)
>     page = browser.new_page()
>     page.goto('https://2captcha.com/demo/cloudflare-turnstile-challenge')
>     time.sleep(1000)
>     browser.close()
> ```
> 
> ![image](https://github.com/user-attachments/assets/177554bb-48ce-45ca-991a-f809ad982984)

I encountered the same problem. In the Linux environment, I passed the Cloudflare check through other plug-ins that simulate clicking, but I was stuck on the page that was verified successfully. But in my development machine (Windows) environment, it is normal. Please ask whether you have solved the problem, and if so, can you analyze with me
