### ISSUE TITLE
How to specify custom browser arguments?

### ISSUE THREAD

**Issue by batreller** [Kaliiiiiiiiii-Vinyzu/patchright-python#7]
I need to replace WebGL Renderer, WebGL Vendor, Languages and maybe some other fingerprints that might be used to trace you with random values
Is there some kind of in-house implementation on the library level? Or is the only way to make it manually by executing some js on each page? I would like to not do it this way to not add any detects accidentally

I would also prefer simulating phone if its possible (not necessary but preferably)
Thanks

**Comment by kaliiiiiiiiii** [comment]
Doesn't work like that haha...
You'll need some custom browser for that to be stable

**Comment by batreller** [comment]
Thanks for quick response!
I need each browser to work with proxy and different fingerprint so it was like completely different user is on the website every time. Can't these details (WebGL Renderer, WebGL Vendor etc.) be used to expose all the "bots"?
Is there already implemented solution for this problem? I know there are some antidetect browsers (like dolphin anty) how do they work?

**Comment by kaliiiiiiiiii** [comment]
> Is there already implemented solution for this problem? I know there are some antidetect browsers (like dolphin anty) how do they work?

Exactly, that's the solution in my view. They've got a modified//patched chromium build.

**Comment by kaliiiiiiiiii** [comment]
> Can't these details (WebGL Renderer, WebGL Vendor etc.) be used to expose all the "bots"?

Depends on your setup. I'd make a difference between "hard" bot detection and fingerprinting. This project currently only aims to cover hard detection.
> Is there already implemented solution for this problem? I know there are some antidetect browsers (like dolphin anty) how do they work?

Exactly, that's the solution in my view. They've got a modified//patched chromium build.
